org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)

## Mod Properties
mod_id=skylogged
mod_name=Skylogged Core
mod_license=MIT
mod_version=1.0.0+pack3.1.0
mod_group_id=net.vercte
mod_authors=Vercte
mod_description=core mod for Skylogged

## Dependencies
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

clutter_no_more_version=1.1.9
mouse_tweaks_version=2.26.1

jei_version=19.27.0.340
emi_version=1.1.22+1.21.1